version: "3.7"
services:
  web:
    build: .
    entrypoint: nodemon /src/app.js
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./src:/app/src
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27027:27017
